// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Hotel_Database_Opgave_15_11_22.Models
{
    [Table("DemoHotel")]
    public partial class DemoHotel
    {
        public DemoHotel()
        {
            DemoRooms = new HashSet<DemoRoom>();
            FacilityNos = new HashSet<Facility>();
        }

        [Key]
        [Column("Hotel_No")]
        public int HotelNo { get; set; }
        [Required]
        [StringLength(30)]
        [Unicode(false)]
        public string Name { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Address { get; set; }

        [InverseProperty("HotelNoNavigation")]
        public virtual ICollection<DemoRoom> DemoRooms { get; set; }

        [ForeignKey("HotelNo")]
        [InverseProperty("HotelNos")]
        public virtual ICollection<Facility> FacilityNos { get; set; }
    }
}