// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Hotel_Database_Opgave_15_11_22.Models
{
    [Table("DemoBooking")]
    public partial class DemoBooking
    {
        [Key]
        [Column("Booking_id")]
        public int BookingId { get; set; }
        [Column("Hotel_No")]
        public int HotelNo { get; set; }
        [Column("Guest_No")]
        public int GuestNo { get; set; }
        [Column("Date_From", TypeName = "date")]
        public DateTime DateFrom { get; set; }
        [Column("Date_To", TypeName = "date")]
        public DateTime DateTo { get; set; }
        [Column("Room_No")]
        public int RoomNo { get; set; }

        [ForeignKey("RoomNo,HotelNo")]
        [InverseProperty("DemoBookings")]
        public virtual DemoRoom DemoRoom { get; set; }
        [ForeignKey("GuestNo")]
        [InverseProperty("DemoBookings")]
        public virtual DemoGuest GuestNoNavigation { get; set; }
    }
}